apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-bluegreen
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: demo

  project: default

  source:
    repoURL: https://github.com/augustus281/deploycraft
    targetRevision: main
    path: k8s/overlays/bluegreen

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ApplyOutOfOrder=true
